In [1]:
import numpy as np

In [10]:
var1=[x/10 for x in list(range(0,101,10))]
var2=[x for x in range(0,91,15)]
var3=[x for x in range(-90,91,15)]
var4=[x for x in range(0,91,15)]
var5=[x for x in range(-90,91,15)]
var6=[x for x in range(-90,91,15)]

In [11]:
var6

[-90, -75, -60, -45, -30, -15, 0, 15, 30, 45, 60, 75, 90]

In [15]:
import numpy as np
from pyDOE import lhs

# Define the number of dimensions and values per dimension
num_dimensions = 6
values_per_dimension = [len(var1), len(var2), len(var3), len(var4), len(var5), len(var6)]

# Generate the Latin Hypercube Sample
lhs_sample = lhs(num_dimensions, samples=1000, criterion='maximin')

# Initialize the sampled indices list
sampled_indices = []

# Select indices based on the LHS sample
for dim in range(num_dimensions):
    dim_indices = np.linspace(0, values_per_dimension[dim] - 1, values_per_dimension[dim])
    selected_indices = np.interp(lhs_sample[:, dim], np.linspace(0, 1, values_per_dimension[dim]), dim_indices)
    sampled_indices.append(selected_indices.astype(int))

# Transpose the sampled indices list
sampled_indices = np.transpose(sampled_indices)

# Print the sampled indices
for indices in sampled_indices:
    print(indices)

[ 5  5  1  3  5 10]
[9 4 3 5 9 4]
[ 9  0 10  3 11  2]
[ 2  1  4  4 10  3]
[ 3  5 10  0 11  0]
[2 4 4 0 7 4]
[ 0  0 11  2  1  0]
[5 1 6 3 9 1]
[ 3  4  3  5  4 11]
[ 8  2  6  5  7 11]
[ 5  2 10  1  2 11]
[ 1  3  1  4 10  9]
[ 7  0  3  1  0 11]
[ 1  4  6  2 10  4]
[9 1 3 0 3 5]
[3 3 7 1 9 4]
[ 9  0  3  1  3 11]
[1 0 0 0 7 6]
[5 0 6 4 4 9]
[5 4 9 3 6 5]
[ 2  5  3  2 11  0]
[2 1 9 3 5 8]
[6 1 0 4 7 2]
[8 3 4 5 0 9]
[3 3 0 3 9 0]
[8 4 8 4 7 7]
[4 0 5 5 8 3]
[1 4 5 3 8 0]
[ 2  2  9  0  9 11]
[3 5 3 3 9 9]
[5 5 6 2 2 5]
[6 5 4 2 8 6]
[ 2  2  0  0 11  0]
[0 1 5 4 2 6]
[2 0 1 1 1 9]
[8 4 3 3 6 2]
[2 5 9 5 7 7]
[4 4 0 0 5 3]
[2 1 6 0 6 7]
[8 1 5 1 1 3]
[4 3 6 5 2 4]
[ 3  4  4  3  8 11]
[ 1  0  1  4 11  8]
[0 1 4 4 0 6]
[4 3 4 4 0 4]
[6 1 2 0 1 3]
[9 2 4 0 1 4]
[ 0  3  2  5 10  3]
[ 6  5 10  1  8  5]
[7 4 5 3 3 8]
[ 8  2  8  5  2 11]
[ 7  0 10  3 11  1]
[ 9  4  9  3  6 10]
[ 8  2 10  2  1  2]
[1 4 9 2 1 5]
[2 4 5 5 9 0]
[ 9  3 11  5  3  6]
[ 1  3  7  5 11  2]
[ 3  2 11  2  3 11]
[2 5 6 1 1 8]
[ 4 

In [18]:
all_samples = []
for indices in sampled_indices:
    all_samples.append([var1[indices[0]], var2[indices[1]], var3[indices[2]], var4[indices[3]], var5[indices[4]], var6[indices[5]]])

In [21]:
import csv
filename = 'samples.csv'

with open(filename, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(all_samples)